// import type { Metadata } from "next";
import ClientLayout from "@/components/ClientLayout";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "My App",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* تمام چیزهای کلاینتی مثل هدر و مودال */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}